apiVersion: v2
name: nadav-pgadmin
description: A Helm chart for pgAdmin
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: postgresql
    version: 12.2.7
    repository: https://charts.bitnami.com/bitnami 
  # - name: prometheus
  #   version: 20.2.0
  #   repository: https://prometheus-community.github.io/helm-charts  
  # - name: kibana
  #   version: 10.2.17
  #   repository: https://charts.bitnami.com/bitnami

