apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: jenkins
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-03-27T13:15:23Z"
  labels:
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-12.0.2
  name: jenkins
  namespace: default
  resourceVersion: "102852"
  uid: 901ed671-0583-4a23-b85f-2664fdce4c47
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.170.150
  clusterIPs:
  - 10.108.170.150
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30783
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30811
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/name: jenkins
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
