apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
    env: "{{ .Values.app.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
      env: "{{ .Values.app.name }}"
  template:
    metadata:
      labels:
        app: pgadmin
        env: "{{ .Values.app.name }}"
    spec:
      containers:
        - name: pgadmin
          image: "{{ .Values.app.image }}"
          ports:
            - containerPort: 80
