apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: test.local
    http:
      paths:
      - path: /
        backend:
          serviceName: pgadmin
          servicePort: 8084
