apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "pgadmin.labels" . | nindent 8 }}
spec:
  ports:
  - port: 8084
    protocol: TCP
    targetPort: 80
  selector:
    app: pgadmin
    env: {{ .Values.env }}
  sessionAffinity: None
  type: NodePort