apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
    env: {{ .Values.env }}
  name: pgadmin-{{ .Values.env }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pgadmin
    env: {{ .Values.env }}
  sessionAffinity: None
  type: ClusterIP
